# Generated by Django 5.0.4 on 2024-05-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category_id',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
